import React from "react";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import styles from "./page.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Soiltrackers Solutions Inc.",
  description: "Privacy Policy for Soiltrackers Solutions Inc. Explaining how we collect, use, and protect personal information under BC PIPA and Canadian privacy laws.",
};

export default function PrivacyPage() {
  return (
    <>
      <Nav primaryCtaLabel="Book Founder Call" primaryCtaHref="/get-started" />
      <main className={styles.main}>
        <article className={styles.container}>
          <header className={styles.header}>
            <div className={styles.eyebrow}>LEGAL &amp; COMPLIANCE</div>
            <h1 className={styles.title}>Privacy Policy</h1>
            <p className={styles.companyLine}>
              <strong>Soiltrackers Solutions Inc.</strong> · Last updated: 15 September 2026
            </p>
            <div className={styles.draftNotice}>
              <strong>DRAFT FOR LEGAL REVIEW.</strong> This is a working draft prepared for transparency and regulatory alignment, not formal legal advice. It outlines our data governance policies under British Columbia&apos;s <em>Personal Information Protection Act</em> (PIPA) and applicable Canadian privacy legislation.
            </div>
          </header>

          <div className={styles.content}>
            <section className={styles.section}>
              <h2>1. Who we are</h2>
              <p>
                Soiltrackers Solutions Inc. (&ldquo;Soiltrackers&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is a company incorporated in British Columbia, Canada. We operate the Soiltrackers platform, a chain-of-custody and compliance system for soil movement, together with the Soiltrackers marketplace and this website.
              </p>
              <p>You can reach us about anything in this policy at:</p>
              <div className={styles.contactCard}>
                <strong>Privacy Officer</strong>
                <p>Soiltrackers Solutions Inc.</p>
                <p>Email: <a href="mailto:privacy@soiltrackers.com">privacy@soiltrackers.com</a></p>
                <p>British Columbia, Canada</p>
              </div>
              <p>
                We are subject to British Columbia&apos;s <em>Personal Information Protection Act</em> (PIPA) and, for personal information collected in the course of commercial activity across provincial or national borders, the federal <em>Personal Information Protection and Electronic Documents Act</em> (PIPEDA).
              </p>
            </section>

            <section className={styles.section}>
              <h2>2. What this policy covers</h2>
              <p>This policy covers personal information we collect through:</p>
              <ul>
                <li>This website, including the founder call booking form and any waitlist or access request forms</li>
                <li>The Soiltrackers platform and marketplace, once you hold an account</li>
                <li>Email, phone, and other direct correspondence with us</li>
                <li>Our business development and outreach activity</li>
              </ul>
              <p>It does not cover sites we link to. Their own policies apply there.</p>
            </section>

            <section className={styles.section}>
              <h2>3. Information we collect</h2>

              <h3>3.1 Information you give us directly</h3>
              <p>
                When you book a founder call, request founding member access, or join a waitlist, we collect your name, business email address, company name, and any other details you choose to provide, such as phone number, role, fleet size, or a description of your operation.
              </p>
              <p>
                When you open an account we collect the information needed to create and administer it, including your name, business contact details, company affiliation, and role.
              </p>

              <h3>3.2 Information generated by using the platform</h3>
              <p>
                Operating the platform necessarily produces records about soil movement. Depending on your configuration this includes:
              </p>
              <ul>
                <li>Source and receiving site identifiers, including location and land-use context</li>
                <li>GPS position data and geofence entry and exit events from connected trackers or telematics providers</li>
                <li>Trip records, including start and end times, assigned truck, assigned driver, and volumes</li>
                <li>Documents and photographs uploaded to a project, including soil characterization and laboratory reports</li>
                <li>Confirmation actions, including who confirmed a trip or signed off on a receipt, and when</li>
                <li>Edit and correction history, including the actor and the stated reason</li>
              </ul>
              <p>
                Some of this is personal information about identifiable individuals, most obviously drivers. Where you are our customer and you supply information about your own personnel or clients, you are responsible for having the authority to provide it to us, and we process it on your behalf.
              </p>

              <h3>3.3 Information collected automatically</h3>
              <p>
                When you visit this website we collect standard technical information including IP address, browser type, device type, pages visited, referring page, and timestamps. This comes from server logs and from any analytics tooling in use.
              </p>

              <h3>3.4 Information from third parties</h3>
              <p>
                We use business data providers to research companies and business contacts in the construction, excavation, and environmental sectors for business development purposes. Information obtained this way is limited to business contact information: name, role, employer, business email address, business phone number.
              </p>
            </section>

            <section className={styles.section}>
              <h2>4. Why we collect it, and your consent</h2>
              <p>
                Under PIPA we collect, use, and disclose personal information only for purposes a reasonable person would consider appropriate in the circumstances, and only with your consent unless the law provides otherwise.
              </p>
              <p>We use personal information to:</p>
              <ul>
                <li>Respond to your enquiry and arrange and conduct a founder call</li>
                <li>Create, administer, and secure your account</li>
                <li>Operate the platform, which includes producing the chain-of-custody records the service exists to produce</li>
                <li>Generate reports, exports, and audit packages at your direction</li>
                <li>Provide support and communicate about the service, including service and security notices</li>
                <li>Improve the platform, understand how it is used, and diagnose faults</li>
                <li>Send commercial electronic messages where permitted, as described in section 5</li>
                <li>Meet legal, regulatory, and accounting obligations</li>
              </ul>
              <p>
                Where consent is required, you may withdraw it at any time on reasonable notice by contacting our Privacy Officer, subject to legal and contractual restrictions. Withdrawing consent may mean we can no longer provide the service. Withdrawing consent does not require us to delete custody records already created, which we may be required to retain, as explained in section 9.
              </p>
            </section>

            <section className={styles.section}>
              <h2>5. Commercial electronic messages (CASL)</h2>
              <p>Canada&apos;s Anti-Spam Legislation governs commercial electronic messages we send.</p>
              <p>
                We send commercial email to business contacts where we have express consent, or where implied consent exists under CASL, including where a business contact&apos;s address is conspicuously published or provided to us without a statement refusing such messages, and our message is relevant to that person&apos;s role.
              </p>
              <p>
                Every commercial message we send identifies Soiltrackers Solutions Inc., gives our contact information, and contains a working unsubscribe mechanism. Unsubscribe requests are honoured without charge and no later than ten business days.
              </p>
              <p>
                If you received a message from us and would rather not hear from us again, use the unsubscribe link or write to <a href="mailto:privacy@soiltrackers.com">privacy@soiltrackers.com</a> and we will remove you.
              </p>
            </section>

            <section className={styles.section}>
              <h2>6. Cookies and analytics</h2>
              <p>
                This website uses cookies and similar technologies that are necessary for the site to work, and may use analytics cookies to understand how the site is used in aggregate.
              </p>
              <p>
                You can configure your browser to refuse cookies. Necessary cookies cannot be refused without affecting the site&apos;s function.
              </p>
            </section>

            <section className={styles.section}>
              <h2>7. Who we share information with</h2>
              <p>We do not sell personal information.</p>
              <p>We share personal information in the following circumstances:</p>

              <div className={styles.tableWrapper}>
                <table className={styles.table}>
                  <thead>
                    <tr>
                      <th>Provider</th>
                      <th>Purpose</th>
                      <th>Data location</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><strong>Vercel Inc.</strong></td>
                      <td>Website and application hosting</td>
                      <td>United States</td>
                    </tr>
                    <tr>
                      <td><strong>Google LLC (Google Workspace)</strong></td>
                      <td>Business email and productivity</td>
                      <td>United States and Canada</td>
                    </tr>
                    <tr>
                      <td><strong>HubSpot Inc.</strong></td>
                      <td>Customer relationship management and marketing email</td>
                      <td>United States</td>
                    </tr>
                    <tr>
                      <td><strong>Supabase</strong></td>
                      <td>Application database</td>
                      <td>Canada / United States</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <p>
                <strong>Within the platform, at your direction.</strong> The service exists to produce records that get shared. When you generate a report, create a shareable export, or invite a client or stakeholder to a project, the information in that record becomes available to the recipients you choose. When you transact through the marketplace, information necessary to the transaction is shared with the counterparty.
              </p>
              <p>
                <strong>Legal and regulatory.</strong> We may disclose personal information where required by law, court order, or a lawful request from a regulator or law enforcement body, or where necessary to establish or defend a legal claim.
              </p>
              <p>
                <strong>Business transaction.</strong> If we are involved in a financing, merger, acquisition, or sale of assets, personal information may be disclosed to the parties involved, subject to appropriate confidentiality protections.
              </p>
            </section>

            <section className={styles.section}>
              <h2>8. Storage outside Canada</h2>
              <p>
                Several of our service providers store and process information in the United States. Information stored in another country is subject to the laws of that country, and may be accessible to the courts, law enforcement, and national security authorities there.
              </p>
              <p>
                By using the service you acknowledge this transfer. If you would prefer your information not be stored outside Canada, contact our Privacy Officer before providing it, and we will tell you whether we can accommodate that.
              </p>
            </section>

            <section className={styles.section}>
              <h2>9. How long we keep it</h2>
              <p>
                We keep personal information only as long as necessary for the purposes it was collected for, or as required by law.
              </p>
              <p>
                <strong>Chain-of-custody records are different from ordinary account data</strong>, and you should understand the distinction. The value of a custody record is that it can be produced later, potentially years later, to demonstrate what happened. Corrections to custody records are append-only: we record the correction and who made it rather than silently overwriting what was there. This means a custody record is not deleted simply because an account closes or a user withdraws consent, and it may be retained for the period required by applicable environmental regulation and statutory limitation periods.
              </p>
              <p>
                Enquiry and marketing records are kept for as long as we have a business relationship or a reasonable prospect of one, and then deleted.
              </p>
            </section>

            <section className={styles.section}>
              <h2>10. Security</h2>
              <p>
                We use administrative, technical, and physical safeguards appropriate to the sensitivity of the information, including encryption in transit, access controls, and restricting access to personnel who need it.
              </p>
              <p>
                No system is perfectly secure and we do not claim otherwise. If a privacy breach creates a real risk of significant harm, we will notify affected individuals and the Office of the Information and Privacy Commissioner for British Columbia as required.
              </p>
            </section>

            <section className={styles.section}>
              <h2>11. Your rights</h2>
              <p>Under PIPA you may:</p>
              <ul>
                <li><strong>Ask what we hold.</strong> Request access to your personal information, and information about how it has been used and to whom it has been disclosed.</li>
                <li><strong>Correct it.</strong> Request correction of inaccurate or incomplete information.</li>
                <li><strong>Withdraw consent.</strong> Subject to the limits in section 4.</li>
              </ul>
              <p>
                Write to <a href="mailto:privacy@soiltrackers.com">privacy@soiltrackers.com</a>. We will respond within 30 days, or tell you why we need an extension. There is no charge for a reasonable request, and we will tell you in advance if a request would attract a fee.
              </p>
              <p>
                If you are not satisfied with our response, you may complain to the Office of the Information and Privacy Commissioner for British Columbia at <a href="https://www.oipc.bc.ca" target="_blank" rel="noopener noreferrer">oipc.bc.ca</a>.
              </p>
            </section>

            <section className={styles.section}>
              <h2>12. Children</h2>
              <p>
                The service is a business tool and is not directed at children. We do not knowingly collect personal information from anyone under the age of majority in their province of residence.
              </p>
            </section>

            <section className={styles.section}>
              <h2>13. Changes to this policy</h2>
              <p>
                We may update this policy. The &ldquo;last updated&rdquo; date at the top reflects the most recent version. Where a change materially affects how we handle personal information already collected, we will give notice and, where required, seek consent.
              </p>
            </section>

            <section className={styles.section}>
              <h2>14. Contact</h2>
              <p>Questions, requests, and complaints go to:</p>
              <div className={styles.contactCard}>
                <strong>Privacy Officer, Soiltrackers Solutions Inc.</strong>
                <p><a href="mailto:privacy@soiltrackers.com">privacy@soiltrackers.com</a></p>
              </div>
            </section>
          </div>

          <footer className={styles.backFooter}>
            <Link href="/" className={styles.backLink}>
              <i className="ri-arrow-left-line"></i> Return to Homepage
            </Link>
          </footer>
        </article>
      </main>
      <Footer />
    </>
  );
}
